### ISSUE TITLE
Problem adding /32 (maybe other subnets) to xfr IP

### ISSUE THREAD

**Issue by jvolkenant** [mail-in-a-box/mailinabox#1658]
Related to #1616

In custom dns, my Secondary dns line has always been this (redacted):
```
xfr:1.2.3.4 ns3.m.domainone.com
```
With current master, if I change this to:
```
xfr:1.2.3.4/32 ns3.m.domainone.com
```
My input is saved, however nsd fails to restart, but this is not reported that there was a failure.

My /etc/nsd/zones.conf gets updated to the following.  There are two entries, one because I specified an IP address, and one that is a lookup of ns3.m.domainone.com.
```
zone:
        name: domainone.com
        zonefile: domainone.com.txt.signed

        notify: 1.2.3.4/32 NOKEY
        provide-xfr: 1.2.3.4/32 NOKEY

        notify: 1.2.3.4 NOKEY
        provide-xfr: 1.2.3.4 NOKEY

zone:
        name: domaintwo.com
        zonefile: domaintwo.com.txt.signed

        notify: 1.2.3.4/32 NOKEY
        provide-xfr: 1.2.3.4/32 NOKEY

        notify: 1.2.3.4 NOKEY
        provide-xfr: 1.2.3.4 NOKEY

zone:
        name: domainthree.com
        zonefile: domainthree.com.txt.signed

        notify: 1.2.3.4/32 NOKEY
        provide-xfr: 1.2.3.4/32 NOKEY

        notify: 1.2.3.4 NOKEY
        provide-xfr: 1.2.3.4 NOKEY

zone:
        name: volkenant.net
        zonefile: volkenant.net.txt.signed

        notify: 1.2.3.4/32 NOKEY
        provide-xfr: 1.2.3.4/32 NOKEY

        notify: 1.2.3.4 NOKEY
        provide-xfr: 1.2.3.4 NOKEY
```

NSD fails to start because 'notify' is a subnet, but should only be an IP address.  Only 'provide-xfr' should be a subnet. man nsd.conf confirms this.

I think this might create a problem as we might need an updated notation if it is the case that you want to notify one IP, but provide xfr to another range.

```xfr:1.2.3.4 provide-xfr:2.0.0.0/24 ns3.m.domainone.com```

Maybe we just require the IP address to be a part of the range.

```xfr:1.2.3.4/24 ns3.m.domainone.com```
That should then result in:
```
        notify: 1.2.3.4 NOKEY
        provide-xfr: 1.2.3.4/32 NOKEY
```
Currently you get a  "'10.20.30.40/24' is not an IPv4 address or subnet." When you try to use the example address 'xfr:10.20.30.40/24' found on the custom dns page.
