### ISSUE TITLE
S3 Backups use only first line of `secret_key.txt`

### ISSUE THREAD

**Issue by mmeidlinger** [mail-in-a-box/mailinabox#2209]
There seems to be an issue with how S3 Backups are encrypted in that it does not actually use the full multi-line key stored in `secret_key.txt` but rather only the first line.

Steps to reproduce (tested on `v60.1`)
1. Create a backup on S3 using the standard process (`cd path/to/mailinabox && management backup.py`) with the below config:
```yaml
min_age_in_days: 7
target: s3://s3.endpoint/s3-bucket/s3-prefix
target_user: AWSACCESSKEYID
target_pass: awssecretaccesskey
```
2. Restore the backup, but only specify the first line of the key to restore:
```bash
export AWS_ACCESS_KEY_ID="AWSACCESSKEYID"
export AWS_SECRET_ACCESS_KEY="awssecretaccesskey"
export S3_URL="s3://s3-bucket/s3-prefix"
export PASSPHRASE=$(head -n1 $STORAGE_ROOT/backups/secret_key.txt)
duplicity restore  $S3_URL /tmp/test-restore
```
