### ISSUE TITLE
Warn user if root-access is allowed

### ISSUE THREAD

**Issue by aspdye** [mail-in-a-box/mailinabox#670]
Currently you are only warned if password-auth is allowed. We should also warn users, if the root user is allowed to login over SSH ;)

**Comment by JoshData** [comment]
The default Digital Ocean setup has the user log in as root, unfortunately.

**Comment by dhpiggott** [comment]
I wrote a guide on using cloud-config user-data to prevent Digital Ocean doing that earlier this month.

Droplets can be created with root disabled and with a single non-root user that has passwordless sudo -- like EC2 does it.

The TL;DR is to enter something like this as the `cloud-config user-data` when creating the Droplet:

```
#cloud-config
timezone: Etc/UTC
users:
  - name: david
    shell: /bin/bash
    gecos: Ubuntu
    groups: [adm, audio, cdrom, dialout, floppy, video, plugdev, dip, netdev, sudo]
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-rsa 0xDEADBEAF...replace.me...0xDEADBEAF== david@ash
disable_root: true
```

(full post is at https://www.piggott.me.uk/2016/01/08/getting-an-ec2-like-oobe-on-digital-ocean-using-cloud-config-user-data/)

I'm just mentioning in case there's any interest in integrating this into the setup guide somehow, at least while Digital Ocean remains the recommended provider?
